---
- targets:
    - 'localhost:9090'
    - 'localhost:9093'
  labels:
    __scheme__: https  # defaults to https
    name: value  # will be added to your metrics as a label, without direct effect

# no additional labels works as well
- targets:
    - 'my.domain'

# A "http[s]://"-prefix is valid (but not required) for the http-modules of the blackbox-exporter.
# Do not use them for regular scrapetargets or your hosts will not show up.
- targets:
    - 'https://wurst.brot' # valid for http-module
    - 'kaese.brot'         # also valid for http-module
    - 'prometheus.io:80'   # tcp_connect needs a port
