---
dependencies:
    - role: mailsender
    - role: letsencrypt
      domains:
        - "alertmanager.{{ server_name }}"
        - "prometheus.{{ server_name }}"
        - "www.{{ server_name }}"
        - "{{ server_name }}"
      le_services:
        - nginx
