---
dependencies:
    - role: mailsender
    - role: letsencrypt
      domains:
        - "alertmanager.{{ public_url }}"
        - "prometheus.{{ public_url }}"
        - "www.{{ public_url }}"
        - "{{ public_url }}"
      le_services:
        - nginx
