modules:
{% for protocol_number in [4, 6] %}
  http_2xx_ipv{{ protocol_number }}:
    prober: http
    http:
      preferred_ip_protocol: "ip{{ protocol_number }}" # defaults to "ip6"
  tcp_connect_ipv{{ protocol_number }}:
    prober: tcp
    tcp:
      preferred_ip_protocol: "ip{{ protocol_number }}" # defaults to "ip6"
  ssh_ipv{{ protocol_number }}:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
      preferred_ip_protocol: "ip{{ protocol_number }}" # defaults to "ip6"
  smtp_starttls_ipv{{ protocol_number }}:
  smtp_starttls:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
      - expect: "^220 "
      - send: "EHLO prober"
      - expect: "^250-STARTTLS"
      - send: "STARTTLS"
      - expect: "^220"
      - starttls: true
      - send: "EHLO prober"
      - expect: "^250-AUTH"
      - send: "QUIT"
      preferred_ip_protocol: "ip{{ protocol_number }}" # defaults to "ip6"
{% endfor %}
